# Form implementation generated from reading ui file 'c:\Users\pasik\Documents\UEB_GUI_PyQt\UEB_GUI_PyQt\ui_parameter_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NewParameterDialog(object):
    def setupUi(self, NewParameterDialog):
        NewParameterDialog.setObjectName("NewParameterDialog")
        NewParameterDialog.resize(602, 94)
        self.gridLayoutWidget = QtWidgets.QWidget(NewParameterDialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 601, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem1, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 4)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 2, 1, 1)
        self.OK_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.OK_pushButton.setObjectName("OK_pushButton")
        self.gridLayout.addWidget(self.OK_pushButton, 3, 5, 1, 1)
        self.ID_Dialog_spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.ID_Dialog_spinBox.setMinimum(1)
        self.ID_Dialog_spinBox.setMaximum(223)
        self.ID_Dialog_spinBox.setObjectName("ID_Dialog_spinBox")
        self.gridLayout.addWidget(self.ID_Dialog_spinBox, 1, 0, 1, 1)
        self.CSV_Dialog_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.CSV_Dialog_lineEdit.setObjectName("CSV_Dialog_lineEdit")
        self.gridLayout.addWidget(self.CSV_Dialog_lineEdit, 1, 1, 1, 4)
        self.Abort_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Abort_pushButton.setObjectName("Abort_pushButton")
        self.gridLayout.addWidget(self.Abort_pushButton, 3, 6, 1, 1)
        self.Type_Dialog_lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Type_Dialog_lineEdit.setObjectName("Type_Dialog_lineEdit")
        self.gridLayout.addWidget(self.Type_Dialog_lineEdit, 1, 5, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 5, 1, 2)

        self.retranslateUi(NewParameterDialog)
        QtCore.QMetaObject.connectSlotsByName(NewParameterDialog)

    def retranslateUi(self, NewParameterDialog):
        _translate = QtCore.QCoreApplication.translate
        NewParameterDialog.setWindowTitle(_translate("NewParameterDialog", "Dialog"))
        self.label.setText(_translate("NewParameterDialog", "ID"))
        self.label_2.setText(_translate("NewParameterDialog", "CSV Spaltenname"))
        self.OK_pushButton.setText(_translate("NewParameterDialog", "OK"))
        self.Abort_pushButton.setText(_translate("NewParameterDialog", "Abbrechen"))
        self.label_3.setText(_translate("NewParameterDialog", "Datentyp"))
